#!/usr/bin/env bash

bwfzf-session-persistence() {
	# invoked as
	# $ bwfzf-session-persistence action:get -v
	# $ bwfzf-session-persistence action:put -dv
	# handle arguments accordingly:
	local argAction="get"
	local argVerbose=false
	local argDebug=false
	bwfzf-argparse "$@"

  if ! hash security 2>/dev/null; then
    echo "Error: You're trying to use `bwfzf-osx-keychain` but the keychain cli command `security` does not exist. Are you sure this is OSX?" >&2
		return 1
	fi

	local outputMode="-q"
	if [[ "${argVerbose}" == true ]]; then
		outputMode="-v"
	fi

	if [[ "${argAction}" == "get" ]]; then
		security -i "${outputMode}" 2>/dev/null <<-EOF
			find-generic-password -a "${USER}" -s bw -w
		EOF
	elif [[ "${argAction}" == "put" ]]; then
		local sessionKey=$( cat )   # take session key from stdin
		security -i "${outputMode}" 2>/dev/null <<-EOF
			add-generic-password -a "${USER}" -s bw -U -T "" -w "${sessionKey}"
		EOF
	fi
}
